name: Frontend CI

on:
  push:
    branches: [ main, docs/update-readme ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    name: Install → Type-check → Lint → Tests → Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./ppg_frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./ppg_frontend

      - name: Type check
        run: npm run type-check
        working-directory: ./ppg_frontend

      # Lint step is temporarily disabled. Uncomment to enable linting in CI.
      # - name: Lint
      #   run: npm run lint
      #   working-directory: ./ppg_frontend

      - name: Run unit & integration tests
        run: |
          npm test --prefix ./ppg_frontend
        env:
          CI: true

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: ./ppg_frontend/coverage

  e2e:
    name: E2E (optional)
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_e2e == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: ./ppg_frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./ppg_frontend

      - name: Run E2E (Playwright)
        run: npm run test:e2e --prefix ./ppg_frontend
        env:
          TARGET_BASE_URL: ${{ secrets.STAGING_URL }}
